<template>
  <div class="d-flex justify-center" style="padding-top: 40px">
    <div style="max-width: 1296px; width: 100%">
      <h1>Privacy Policy</h1>
      <br />
      <div v-for="(item, index) in arr" :key="index">
        <h3>{{ index + 1 }}. {{ item.title }}</h3>
        <p>
          {{ item.content }}
        </p>
        <br />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
const arr = [
  {
    title: "Information Collection",
    content:
      "We collect information that users provide when they register, including name, email address, payment information, etc. We may also collect videos and other related data generated by users when they use the service.",
  },
  {
    title: "Information Use",
    content:
      "We use the information we collect to provide and improve our services, process payments, communicate with users, and comply with legal obligations.",
  },
  {
    title: "Information Sharing",
    content:
      "We will not sell or rent users' personal information to third parties. We may share information with trusted third-party service providers to help us provide the service, but these third parties must comply with strict confidentiality obligations.",
  },
  {
    title: "Data Security",
    content:
      "We take reasonable measures to protect the security of user information, including using encryption technology and secure servers. However, no method of transmission or electronic storage over the Internet is 100% secure.",
  },
  {
    title: "User Rights",
    content:
      "Users can access, correct, or delete their personal information at any time. Users can also choose to opt out of our marketing communications.",
  },
  {
    title: "Changes to Privacy Policy",
    content:
      "We may update the Privacy Policy from time to time. Any changes will be posted on this page and notified to users via email before the changes take effect.",
  },
];
</script>
